//! Static preview registrations for gap stubs in this crate.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
pub fn all() -> &'static [&'static PreviewRegistration] {
    use crate::{
        SCHEDULERCALENDARDRAGINTERACTIONS_PREVIEW_REGISTRATION,
        SCHEDULERCALENDAREDITING_PREVIEW_REGISTRATION,
        SCHEDULERCALENDAREVENTS_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARFILTERING_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARIMPORTEXPORT_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARLAZYLOADING_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARLOCALIZATION_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARNAVIGATION_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARPREFERENCES_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARRESOURCES_PREVIEW_REGISTRATION,
        SCHEDULERCALENDARVIEWS_PREVIEW_REGISTRATION, SCHEDULERCALENDAR_PREVIEW_REGISTRATION,
        SCHEDULERQUICKSTART_PREVIEW_REGISTRATION, SCHEDULERRECURRINGEVENTS_PREVIEW_REGISTRATION,
        SCHEDULERSLOTSDOC_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEDRAGINTERACTIONS_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEEDITING_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEEVENTS_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEFILTERING_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEIMPORTEXPORT_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINELAZYLOADING_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINELOCALIZATION_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINENAVIGATION_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEPREFERENCES_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEPRESETS_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINERESOURCES_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINEVIRTUALIZATION_PREVIEW_REGISTRATION,
        SCHEDULERTIMELINE_PREVIEW_REGISTRATION, SCHEDULERTIMEZONE_PREVIEW_REGISTRATION,
    };

    static REGS: &[&PreviewRegistration] = &[
        &SCHEDULERCALENDAR_PREVIEW_REGISTRATION,
        &SCHEDULERSLOTSDOC_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINE_PREVIEW_REGISTRATION,
        &SCHEDULERQUICKSTART_PREVIEW_REGISTRATION,
        &SCHEDULERRECURRINGEVENTS_PREVIEW_REGISTRATION,
        &SCHEDULERTIMEZONE_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARVIEWS_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARNAVIGATION_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDAREVENTS_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARRESOURCES_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARDRAGINTERACTIONS_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDAREDITING_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARFILTERING_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARLAZYLOADING_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARLOCALIZATION_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARPREFERENCES_PREVIEW_REGISTRATION,
        &SCHEDULERCALENDARIMPORTEXPORT_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEPRESETS_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEVIRTUALIZATION_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINENAVIGATION_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEEVENTS_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINERESOURCES_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEDRAGINTERACTIONS_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEEDITING_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEFILTERING_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINELAZYLOADING_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINELOCALIZATION_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEPREFERENCES_PREVIEW_REGISTRATION,
        &SCHEDULERTIMELINEIMPORTEXPORT_PREVIEW_REGISTRATION,
    ];
    REGS
}

#[cfg(not(feature = "preview"))]
pub fn all() -> &'static [&'static PreviewRegistration] {
    &[]
}
