//! Static preview registrations for gap stubs in this crate.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
pub fn all() -> &'static [&'static PreviewRegistration] {
    use crate::preview::{
        BARCHARTANIMATIONPREVIEW_PREVIEW_REGISTRATION, CHARTEMBEDPREVIEW_PREVIEW_REGISTRATION,
        CHARTSHIGHLIGHTINGPREVIEW_PREVIEW_REGISTRATION, CHARTSKEYBOARDPREVIEW_PREVIEW_REGISTRATION,
        CHARTSLABELPREVIEW_PREVIEW_REGISTRATION, CHARTSLEGENDPREVIEW_PREVIEW_REGISTRATION,
        CHARTSSTYLINGPREVIEW_PREVIEW_REGISTRATION, CHARTSTOOLTIPPREVIEW_PREVIEW_REGISTRATION,
        CHARTSZOOMPAN_PREVIEW_REGISTRATION,
    };
    use crate::{
        AREACHART_PREVIEW_REGISTRATION, BARCHART_PREVIEW_REGISTRATION,
        CHARTCOMPOSITION_PREVIEW_REGISTRATION, CHARTCONTAINER_PREVIEW_REGISTRATION,
        CHARTSAXIS_PREVIEW_REGISTRATION, CHARTSTACKING_PREVIEW_REGISTRATION,
        DATASETINTEGRATION_PREVIEW_REGISTRATION, GAUGE_PREVIEW_REGISTRATION,
        HEATMAP_PREVIEW_REGISTRATION, LINECHART_PREVIEW_REGISTRATION,
        PIECHART_PREVIEW_REGISTRATION, SCATTERCHART_PREVIEW_REGISTRATION,
        SPARKLINE_PREVIEW_REGISTRATION,
    };

    static REGS: &[&PreviewRegistration] = &[
        &BARCHART_PREVIEW_REGISTRATION,
        &BARCHARTANIMATIONPREVIEW_PREVIEW_REGISTRATION,
        &LINECHART_PREVIEW_REGISTRATION,
        &AREACHART_PREVIEW_REGISTRATION,
        &PIECHART_PREVIEW_REGISTRATION,
        &SCATTERCHART_PREVIEW_REGISTRATION,
        &SPARKLINE_PREVIEW_REGISTRATION,
        &GAUGE_PREVIEW_REGISTRATION,
        &HEATMAP_PREVIEW_REGISTRATION,
        &CHARTSAXIS_PREVIEW_REGISTRATION,
        &CHARTSKEYBOARDPREVIEW_PREVIEW_REGISTRATION,
        &CHARTSLEGENDPREVIEW_PREVIEW_REGISTRATION,
        &CHARTSTOOLTIPPREVIEW_PREVIEW_REGISTRATION,
        &CHARTCOMPOSITION_PREVIEW_REGISTRATION,
        &CHARTEMBEDPREVIEW_PREVIEW_REGISTRATION,
        &CHARTCONTAINER_PREVIEW_REGISTRATION,
        &CHARTSTACKING_PREVIEW_REGISTRATION,
        &CHARTSZOOMPAN_PREVIEW_REGISTRATION,
        &CHARTSHIGHLIGHTINGPREVIEW_PREVIEW_REGISTRATION,
        &CHARTSSTYLINGPREVIEW_PREVIEW_REGISTRATION,
        &CHARTSLABELPREVIEW_PREVIEW_REGISTRATION,
        &DATASETINTEGRATION_PREVIEW_REGISTRATION,
    ];
    REGS
}

#[cfg(not(feature = "preview"))]
pub fn all() -> &'static [&'static PreviewRegistration] {
    &[]
}
