//! Static preview registrations for DataTable documentation pages.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
pub fn all() -> &'static [&'static PreviewRegistration] {
    use crate::{
        DATATABLEADVANCEDDOC_PREVIEW_REGISTRATION,
        DATATABLECOLUMNDEFINITIONDOC_PREVIEW_REGISTRATION,
        DATATABLECOLUMNSDOC_PREVIEW_REGISTRATION, DATATABLEDATASOURCEDOC_PREVIEW_REGISTRATION,
        DATATABLEEDITINGDOC_PREVIEW_REGISTRATION, DATATABLEEXPORTDOC_PREVIEW_REGISTRATION,
        DATATABLERENDERINGDOC_PREVIEW_REGISTRATION, DATATABLEROWSDOC_PREVIEW_REGISTRATION,
        DATATABLESELECTIONDOC_PREVIEW_REGISTRATION, DATATABLESLOTSDOC_PREVIEW_REGISTRATION,
        DATATABLESORTINGFILTERINGDOC_PREVIEW_REGISTRATION, DATATABLESTATEDOC_PREVIEW_REGISTRATION,
        DATATABLE_PREVIEW_REGISTRATION,
    };

    static REGS: &[&PreviewRegistration] = &[
        &DATATABLE_PREVIEW_REGISTRATION,
        &DATATABLESLOTSDOC_PREVIEW_REGISTRATION,
        &DATATABLECOLUMNDEFINITIONDOC_PREVIEW_REGISTRATION,
        &DATATABLECOLUMNSDOC_PREVIEW_REGISTRATION,
        &DATATABLEROWSDOC_PREVIEW_REGISTRATION,
        &DATATABLEEDITINGDOC_PREVIEW_REGISTRATION,
        &DATATABLESORTINGFILTERINGDOC_PREVIEW_REGISTRATION,
        &DATATABLEDATASOURCEDOC_PREVIEW_REGISTRATION,
        &DATATABLESELECTIONDOC_PREVIEW_REGISTRATION,
        &DATATABLEEXPORTDOC_PREVIEW_REGISTRATION,
        &DATATABLERENDERINGDOC_PREVIEW_REGISTRATION,
        &DATATABLEADVANCEDDOC_PREVIEW_REGISTRATION,
        &DATATABLESTATEDOC_PREVIEW_REGISTRATION,
    ];
    REGS
}

#[cfg(not(feature = "preview"))]
pub fn all() -> &'static [&'static PreviewRegistration] {
    &[]
}
