use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
use crate::app_bar::APPBAR_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::button::BUTTON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::card::{
    CARDBUTTONAREA_PREVIEW_REGISTRATION, CARDCONTENT_PREVIEW_REGISTRATION,
    CARDFOOTER_PREVIEW_REGISTRATION, CARDHEADER_PREVIEW_REGISTRATION,
    CARDMEDIA_PREVIEW_REGISTRATION, CARDPREVIEW_PREVIEW_REGISTRATION, CARD_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::code::CODE_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::data::{
    AVATARGROUP_PREVIEW_REGISTRATION, AVATAR_PREVIEW_REGISTRATION, BREADCRUMB_PREVIEW_REGISTRATION,
    IMAGE_PREVIEW_REGISTRATION, LINK_PREVIEW_REGISTRATION, LIST_PREVIEW_REGISTRATION,
    PERSONA_PREVIEW_REGISTRATION, TABLE_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::divider::DIVIDER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::extensions::LOADINGBAR_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::extensions::THEMEPREVIEWMARKER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::feedback::{
    BADGE_PREVIEW_REGISTRATION, COUNTERBADGE_PREVIEW_REGISTRATION, DIALOG_PREVIEW_REGISTRATION,
    MESSAGEBAR_PREVIEW_REGISTRATION, PRESENCEBADGE_PREVIEW_REGISTRATION,
    PROGRESSBAR_PREVIEW_REGISTRATION, SKELETON_PREVIEW_REGISTRATION, SPINNER_PREVIEW_REGISTRATION,
    TOAST_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::flex::FLEX_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::floating_button::FLOATINGBUTTON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::action_menu_button::ACTIONMENUBUTTON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::auto_complete::AUTOCOMPLETE_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::button_group::BUTTONGROUP_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::calendar::CALENDAR_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::checkbox::CHECKBOX_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::color_picker::COLORPICKER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::combobox::COMBOBOX_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::compound_button::COMPOUNDBUTTON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::date_picker::DATEPICKER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::dropdown::DROPDOWN_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::field::FIELD_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::info_label::INFOLABEL_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::input::INPUT_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::label::LABEL_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::menu_button::MENUBUTTON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::numeric_stepper::NUMERICSTEPPER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::radio::RADIO_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::search_box::SEARCHBOX_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::select::SELECT_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::slider::SLIDER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::swatch_picker::SWATCHPICKER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::switch::SWITCH_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::textarea::TEXTAREA_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::time_picker::TIMEPICKER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::toggle_button::TOGGLEBUTTON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::transfer_list::TRANSFERLIST_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::forms::upload::UPLOAD_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::grid::GRID_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::icon::ICON_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::layout::{CONTENTWITHASIDE_PREVIEW_REGISTRATION, LAYOUT_PREVIEW_REGISTRATION};
#[cfg(feature = "preview")]
use crate::layout_box::BOX_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::material::MATERIAL_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::navigation::anchor::ANCHOR_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::navigation::back_to_top::BACKTOTOP_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::navigation::floating_actions_menu::FLOATINGACTIONSMENU_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::navigation::{
    ACCORDION_PREVIEW_REGISTRATION, CAROUSELSTEPPER_PREVIEW_REGISTRATION,
    CAROUSEL_PREVIEW_REGISTRATION, DRAWER_PREVIEW_REGISTRATION, MENU_PREVIEW_REGISTRATION,
    NAVIGATION_PREVIEW_REGISTRATION, OVERFLOW_PREVIEW_REGISTRATION, POPOVER_PREVIEW_REGISTRATION,
    SPOTLIGHTPOPOVER_PREVIEW_REGISTRATION, SPOTLIGHTTIP_PREVIEW_REGISTRATION,
    SPOTLIGHTTOUR_PREVIEW_REGISTRATION, TOOLBAR_PREVIEW_REGISTRATION, TOOLTIP_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::overlay::backdrop::BACKDROP_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::pagination::PAGINATION_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::rating::{RATINGDISPLAY_PREVIEW_REGISTRATION, RATING_PREVIEW_REGISTRATION};
#[cfg(feature = "preview")]
use crate::scroll_area::SCROLLAREA_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::space::SPACE_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::stack::STACK_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::tab_list::TABLIST_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::tag::TAGPICKER_PREVIEW_REGISTRATION;
#[cfg(feature = "preview")]
use crate::tag::{
    INTERACTIONTAG_PREVIEW_REGISTRATION, TAGGROUP_PREVIEW_REGISTRATION, TAG_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::tree::{RICHTREE_PREVIEW_REGISTRATION, TREE_PREVIEW_REGISTRATION};

orbital_macros::preview_registrations! {
    &FLEX_PREVIEW_REGISTRATION,
    &BUTTON_PREVIEW_REGISTRATION,
    &MATERIAL_PREVIEW_REGISTRATION,
    &APPBAR_PREVIEW_REGISTRATION,
    &BOX_PREVIEW_REGISTRATION,
    &LAYOUT_PREVIEW_REGISTRATION,
    &CONTENTWITHASIDE_PREVIEW_REGISTRATION,
    &ICON_PREVIEW_REGISTRATION,
    &SCROLLAREA_PREVIEW_REGISTRATION,
    &NAVIGATION_PREVIEW_REGISTRATION,
    &TABLIST_PREVIEW_REGISTRATION,
    &CODE_PREVIEW_REGISTRATION,
    &CARD_PREVIEW_REGISTRATION,
    &CARDHEADER_PREVIEW_REGISTRATION,
    &CARDMEDIA_PREVIEW_REGISTRATION,
    &CARDCONTENT_PREVIEW_REGISTRATION,
    &CARDBUTTONAREA_PREVIEW_REGISTRATION,
    &CARDFOOTER_PREVIEW_REGISTRATION,
    &CARDPREVIEW_PREVIEW_REGISTRATION,
    &INPUT_PREVIEW_REGISTRATION,
    &BUTTONGROUP_PREVIEW_REGISTRATION,
    &COMPOUNDBUTTON_PREVIEW_REGISTRATION,
    &ACTIONMENUBUTTON_PREVIEW_REGISTRATION,
    &CALENDAR_PREVIEW_REGISTRATION,
    &DATEPICKER_PREVIEW_REGISTRATION,
    &TIMEPICKER_PREVIEW_REGISTRATION,
    &FIELD_PREVIEW_REGISTRATION,
    &INFOLABEL_PREVIEW_REGISTRATION,
    &LABEL_PREVIEW_REGISTRATION,
    &SELECT_PREVIEW_REGISTRATION,
    &RADIO_PREVIEW_REGISTRATION,
    &CHECKBOX_PREVIEW_REGISTRATION,
    &COLORPICKER_PREVIEW_REGISTRATION,
    &SWATCHPICKER_PREVIEW_REGISTRATION,
    &COMBOBOX_PREVIEW_REGISTRATION,
    &AUTOCOMPLETE_PREVIEW_REGISTRATION,
    &SWITCH_PREVIEW_REGISTRATION,
    &SLIDER_PREVIEW_REGISTRATION,
    &NUMERICSTEPPER_PREVIEW_REGISTRATION,
    &TEXTAREA_PREVIEW_REGISTRATION,
    &SEARCHBOX_PREVIEW_REGISTRATION,
    &DROPDOWN_PREVIEW_REGISTRATION,
    &ACCORDION_PREVIEW_REGISTRATION,
    &DRAWER_PREVIEW_REGISTRATION,
    &FLOATINGACTIONSMENU_PREVIEW_REGISTRATION,
    &TOOLTIP_PREVIEW_REGISTRATION,
    &POPOVER_PREVIEW_REGISTRATION,
    &SPOTLIGHTPOPOVER_PREVIEW_REGISTRATION,
    &SPOTLIGHTTIP_PREVIEW_REGISTRATION,
    &SPOTLIGHTTOUR_PREVIEW_REGISTRATION,
    &MENU_PREVIEW_REGISTRATION,
    &DIALOG_PREVIEW_REGISTRATION,
    &BACKDROP_PREVIEW_REGISTRATION,
    &MESSAGEBAR_PREVIEW_REGISTRATION,
    &PROGRESSBAR_PREVIEW_REGISTRATION,
    &SPINNER_PREVIEW_REGISTRATION,
    &SKELETON_PREVIEW_REGISTRATION,
    &BADGE_PREVIEW_REGISTRATION,
    &TOAST_PREVIEW_REGISTRATION,
    &MENUBUTTON_PREVIEW_REGISTRATION,
    &TOGGLEBUTTON_PREVIEW_REGISTRATION,
    &TRANSFERLIST_PREVIEW_REGISTRATION,
    &GRID_PREVIEW_REGISTRATION,
    &TABLE_PREVIEW_REGISTRATION,
    &AVATAR_PREVIEW_REGISTRATION,
    &AVATARGROUP_PREVIEW_REGISTRATION,
    &PRESENCEBADGE_PREVIEW_REGISTRATION,
    &COUNTERBADGE_PREVIEW_REGISTRATION,
    &PERSONA_PREVIEW_REGISTRATION,
    &RATING_PREVIEW_REGISTRATION,
    &RATINGDISPLAY_PREVIEW_REGISTRATION,
    &LINK_PREVIEW_REGISTRATION,
    &LIST_PREVIEW_REGISTRATION,
    &IMAGE_PREVIEW_REGISTRATION,
    &BREADCRUMB_PREVIEW_REGISTRATION,
    &OVERFLOW_PREVIEW_REGISTRATION,
    &CAROUSEL_PREVIEW_REGISTRATION,
    &CAROUSELSTEPPER_PREVIEW_REGISTRATION,
    &TOOLBAR_PREVIEW_REGISTRATION,
    &DIVIDER_PREVIEW_REGISTRATION,
    &SPACE_PREVIEW_REGISTRATION,
    &STACK_PREVIEW_REGISTRATION,
    &UPLOAD_PREVIEW_REGISTRATION,
    &ANCHOR_PREVIEW_REGISTRATION,
    &FLOATINGBUTTON_PREVIEW_REGISTRATION,
    &BACKTOTOP_PREVIEW_REGISTRATION,
    &TAG_PREVIEW_REGISTRATION,
    &TAGGROUP_PREVIEW_REGISTRATION,
    &INTERACTIONTAG_PREVIEW_REGISTRATION,
    &TAGPICKER_PREVIEW_REGISTRATION,
    &LOADINGBAR_PREVIEW_REGISTRATION,
    &THEMEPREVIEWMARKER_PREVIEW_REGISTRATION,
    &TREE_PREVIEW_REGISTRATION,
    &RICHTREE_PREVIEW_REGISTRATION,
    &PAGINATION_PREVIEW_REGISTRATION
}
