//! Static preview registrations for motion catalog pages.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
pub fn all() -> &'static [&'static PreviewRegistration] {
    use crate::preview::{
        MOTIONATOMSGALLERY_PREVIEW_REGISTRATION,
        MOTIONCHOREOGRAPHYSTAGGERDEMO_PREVIEW_REGISTRATION, MOTIONOVERVIEW_PREVIEW_REGISTRATION,
        MOTIONREDUCEDMOTIONDEMO_PREVIEW_REGISTRATION, MOTIONSETTINGSDEMO_PREVIEW_REGISTRATION,
        MOTIONTOKENSREFERENCE_PREVIEW_REGISTRATION, ORBITALPRESENCEGROUP_PREVIEW_REGISTRATION,
        ORBITALPRESENCE_PREVIEW_REGISTRATION,
    };

    static REGS: &[&PreviewRegistration] = &[
        &MOTIONOVERVIEW_PREVIEW_REGISTRATION,
        &MOTIONATOMSGALLERY_PREVIEW_REGISTRATION,
        &ORBITALPRESENCE_PREVIEW_REGISTRATION,
        &MOTIONCHOREOGRAPHYSTAGGERDEMO_PREVIEW_REGISTRATION,
        &ORBITALPRESENCEGROUP_PREVIEW_REGISTRATION,
        &MOTIONTOKENSREFERENCE_PREVIEW_REGISTRATION,
        &MOTIONSETTINGSDEMO_PREVIEW_REGISTRATION,
        &MOTIONREDUCEDMOTIONDEMO_PREVIEW_REGISTRATION,
    ];
    REGS
}

#[cfg(not(feature = "preview"))]
pub fn all() -> &'static [&'static PreviewRegistration] {
    &[]
}
