//! Static preview registrations for history documentation pages.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
use crate::products::history::docs::{
    HISTORYDATASOURCEDOC_PREVIEW_REGISTRATION, HISTORYDATEDIVIDERSDOC_PREVIEW_REGISTRATION,
    HISTORYEMBEDDOC_PREVIEW_REGISTRATION, HISTORYFILTERDOC_PREVIEW_REGISTRATION,
    HISTORYGROUPINGDOC_PREVIEW_REGISTRATION, HISTORYHANDLEDOC_PREVIEW_REGISTRATION,
    HISTORYLAYOUTDOC_PREVIEW_REGISTRATION, HISTORYLIVETRANSPORTDOC_PREVIEW_REGISTRATION,
    HISTORYLIVEUPDATEDOC_PREVIEW_REGISTRATION, HISTORYLOADINGDOC_PREVIEW_REGISTRATION,
    HISTORYLOCALIZATIONDOC_PREVIEW_REGISTRATION, HISTORYMARKDOWNDOC_PREVIEW_REGISTRATION,
    HISTORYMULTIDIFFDOC_PREVIEW_REGISTRATION, HISTORYPAGEDDOC_PREVIEW_REGISTRATION,
    HISTORYREFRESHDOC_PREVIEW_REGISTRATION, HISTORYRENDERERSDOC_PREVIEW_REGISTRATION,
    HISTORYSCROLLLOADDOC_PREVIEW_REGISTRATION, HISTORYSERVERFILTERDOC_PREVIEW_REGISTRATION,
    HISTORYSLOTSDOC_PREVIEW_REGISTRATION, HISTORYSORTDOC_PREVIEW_REGISTRATION,
    HISTORYTIMEZONEBUCKETSDOC_PREVIEW_REGISTRATION, HISTORYTIMEZONEDISPLAYDOC_PREVIEW_REGISTRATION,
    HISTORYVIRTUALIZEDDOC_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::products::history::HISTORYTIMELINE_PREVIEW_REGISTRATION;

orbital_macros::preview_registrations! {
    &HISTORYTIMELINE_PREVIEW_REGISTRATION,
    &HISTORYLAYOUTDOC_PREVIEW_REGISTRATION,
    &HISTORYDATASOURCEDOC_PREVIEW_REGISTRATION,
    &HISTORYLOADINGDOC_PREVIEW_REGISTRATION,
    &HISTORYSLOTSDOC_PREVIEW_REGISTRATION,
    &HISTORYRENDERERSDOC_PREVIEW_REGISTRATION,
    &HISTORYLOCALIZATIONDOC_PREVIEW_REGISTRATION,
    &HISTORYDATEDIVIDERSDOC_PREVIEW_REGISTRATION,
    &HISTORYMULTIDIFFDOC_PREVIEW_REGISTRATION,
    &HISTORYEMBEDDOC_PREVIEW_REGISTRATION,
    &HISTORYHANDLEDOC_PREVIEW_REGISTRATION,
    &HISTORYREFRESHDOC_PREVIEW_REGISTRATION,
    &HISTORYTIMEZONEBUCKETSDOC_PREVIEW_REGISTRATION,
    &HISTORYLIVEUPDATEDOC_PREVIEW_REGISTRATION,
    &HISTORYTIMEZONEDISPLAYDOC_PREVIEW_REGISTRATION,
    &HISTORYFILTERDOC_PREVIEW_REGISTRATION,
    &HISTORYSORTDOC_PREVIEW_REGISTRATION,
    &HISTORYPAGEDDOC_PREVIEW_REGISTRATION,
    &HISTORYSCROLLLOADDOC_PREVIEW_REGISTRATION,
    &HISTORYSERVERFILTERDOC_PREVIEW_REGISTRATION,
    &HISTORYVIRTUALIZEDDOC_PREVIEW_REGISTRATION,
    &HISTORYMARKDOWNDOC_PREVIEW_REGISTRATION,
    &HISTORYLIVETRANSPORTDOC_PREVIEW_REGISTRATION,
    &HISTORYGROUPINGDOC_PREVIEW_REGISTRATION,
}
