//! Static preview registrations for hydrate builds where `inventory` may be empty.

use super::PreviewRegistration;

#[cfg(feature = "preview")]
use crate::components::{
    AUTOGRID_PREVIEW_REGISTRATION, CONTAINER_PREVIEW_REGISTRATION, DEMOBOX_PREVIEW_REGISTRATION,
    EMPTYSTATE_PREVIEW_REGISTRATION, FEATURESECTION_PREVIEW_REGISTRATION,
    HEROSECTION_PREVIEW_REGISTRATION, IDENTITYCARD_PREVIEW_REGISTRATION,
    ORBITALINFINITESCROLL_PREVIEW_REGISTRATION, PAGINATOR_PREVIEW_REGISTRATION,
    STATCARD_PREVIEW_REGISTRATION, STEPPER_PREVIEW_REGISTRATION, TEXTPREVIEW_PREVIEW_REGISTRATION,
};
#[cfg(feature = "preview")]
use crate::preview::BOOTLOADERGUIDEPREVIEW_PREVIEW_REGISTRATION;

orbital_macros::preview_registrations! {
    &BOOTLOADERGUIDEPREVIEW_PREVIEW_REGISTRATION,
    &DEMOBOX_PREVIEW_REGISTRATION,
    &ORBITALINFINITESCROLL_PREVIEW_REGISTRATION,
    &AUTOGRID_PREVIEW_REGISTRATION,
    &CONTAINER_PREVIEW_REGISTRATION,
    &STATCARD_PREVIEW_REGISTRATION,
    &EMPTYSTATE_PREVIEW_REGISTRATION,
    &STEPPER_PREVIEW_REGISTRATION,
    &PAGINATOR_PREVIEW_REGISTRATION,
    &TEXTPREVIEW_PREVIEW_REGISTRATION,
    &IDENTITYCARD_PREVIEW_REGISTRATION,
    &HEROSECTION_PREVIEW_REGISTRATION,
    &FEATURESECTION_PREVIEW_REGISTRATION
}
