//! Static preview registrations for gap stubs in this crate.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
use crate::{
    DATECALENDAR_PREVIEW_REGISTRATION, DATEFIELD_PREVIEW_REGISTRATION,
    DATEPICKERSACCESSIBILITYGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSCUSTOMCOMPONENTSGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSCUSTOMFIELDGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSCUSTOMLAYOUTGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSCUSTOMOPENGUIDE_PREVIEW_REGISTRATION, DATEPICKERSOVERVIEWGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSPLAYGROUNDGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSSHORTCUTSGUIDE_PREVIEW_REGISTRATION, DATEPICKERSTIMEZONEGUIDE_PREVIEW_REGISTRATION,
    DATEPICKERSVALIDATIONGUIDE_PREVIEW_REGISTRATION, DATERANGECALENDAR_PREVIEW_REGISTRATION,
    DATERANGEFIELD_PREVIEW_REGISTRATION, DATERANGEPICKER_PREVIEW_REGISTRATION,
    DATETIMEFIELD_PREVIEW_REGISTRATION, DATETIMELOCALE_PREVIEW_REGISTRATION,
    DATETIMEPICKER_PREVIEW_REGISTRATION, DATETIMERANGEFIELD_PREVIEW_REGISTRATION,
    DATETIMERANGEPICKER_PREVIEW_REGISTRATION, DIGITALCLOCK_PREVIEW_REGISTRATION,
    TIMECLOCK_PREVIEW_REGISTRATION, TIMEFIELD_PREVIEW_REGISTRATION,
    TIMERANGEFIELD_PREVIEW_REGISTRATION, TIMERANGEPICKER_PREVIEW_REGISTRATION,
};

orbital_macros::preview_registrations! {
    &DATETIMELOCALE_PREVIEW_REGISTRATION,
    &DATEPICKERSOVERVIEWGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSPLAYGROUNDGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSVALIDATIONGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSSHORTCUTSGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSTIMEZONEGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSACCESSIBILITYGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSCUSTOMCOMPONENTSGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSCUSTOMLAYOUTGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSCUSTOMFIELDGUIDE_PREVIEW_REGISTRATION,
    &DATEPICKERSCUSTOMOPENGUIDE_PREVIEW_REGISTRATION,
    &DATETIMEPICKER_PREVIEW_REGISTRATION,
    &DATERANGEPICKER_PREVIEW_REGISTRATION,
    &TIMERANGEPICKER_PREVIEW_REGISTRATION,
    &DATETIMERANGEPICKER_PREVIEW_REGISTRATION,
    &DATECALENDAR_PREVIEW_REGISTRATION,
    &DATERANGECALENDAR_PREVIEW_REGISTRATION,
    &DATEFIELD_PREVIEW_REGISTRATION,
    &TIMEFIELD_PREVIEW_REGISTRATION,
    &DATETIMEFIELD_PREVIEW_REGISTRATION,
    &DATERANGEFIELD_PREVIEW_REGISTRATION,
    &TIMERANGEFIELD_PREVIEW_REGISTRATION,
    &DATETIMERANGEFIELD_PREVIEW_REGISTRATION,
    &TIMECLOCK_PREVIEW_REGISTRATION,
    &DIGITALCLOCK_PREVIEW_REGISTRATION,
}
