//! Static preview registrations for discussion components.

use crate::preview::PreviewRegistration;

#[cfg(feature = "preview")]
pub fn all() -> &'static [&'static PreviewRegistration] {
    use crate::products::discussion::docs::{
        DISCUSSIONAGENTPARTSDOC_PREVIEW_REGISTRATION, DISCUSSIONCITATIONSDOC_PREVIEW_REGISTRATION,
        DISCUSSIONCOMPOSERDOC_PREVIEW_REGISTRATION, DISCUSSIONCUSTOMAREASDOC_PREVIEW_REGISTRATION,
        DISCUSSIONEVENTSDOC_PREVIEW_REGISTRATION, DISCUSSIONINTEGRATIONDOC_PREVIEW_REGISTRATION,
        DISCUSSIONLOCALIZATIONDOC_PREVIEW_REGISTRATION, DISCUSSIONOVERLAYSDOC_PREVIEW_REGISTRATION,
        DISCUSSIONPARTSDOC_PREVIEW_REGISTRATION, DISCUSSIONREPLIESDOC_PREVIEW_REGISTRATION,
        DISCUSSIONREPLYANCHORDOC_PREVIEW_REGISTRATION, DISCUSSIONSLOTSDOC_PREVIEW_REGISTRATION,
        DISCUSSIONTREENAVIGATIONDOC_PREVIEW_REGISTRATION,
        DISCUSSIONVIEWMODESDOC_PREVIEW_REGISTRATION,
    };
    use crate::products::discussion::DISCUSSIONTHREAD_PREVIEW_REGISTRATION;

    static REGS: &[&PreviewRegistration] = &[
        &DISCUSSIONTHREAD_PREVIEW_REGISTRATION,
        &DISCUSSIONREPLIESDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONTREENAVIGATIONDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONREPLYANCHORDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONVIEWMODESDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONCOMPOSERDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONPARTSDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONCITATIONSDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONLOCALIZATIONDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONOVERLAYSDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONCUSTOMAREASDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONSLOTSDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONEVENTSDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONAGENTPARTSDOC_PREVIEW_REGISTRATION,
        &DISCUSSIONINTEGRATIONDOC_PREVIEW_REGISTRATION,
    ];
    REGS
}

#[cfg(not(feature = "preview"))]
pub fn all() -> &'static [&'static PreviewRegistration] {
    &[]
}
